export const COMMUNITY_CONFIG = {
  DEFAULT_RADIUS_KM: 50,
  MIN_RADIUS_KM: 5,
  MAX_RADIUS_KM: 200,
  ALLOWED_RADIUS_OPTIONS: [5, 10, 20, 50, 100, 200] as const,

  GEOHASH_PRECISION: 5,

  CHAT_MESSAGE_MAX_LENGTH: 1000,
  CHAT_MESSAGE_MIN_LENGTH: 1,
  CHAT_MEDIA_MAX_COUNT: 4,

  STORY_EXPIRE_HOURS: 24,
  STORY_VIDEO_MAX_DURATION_SEC: 30,

  CHAT_DEFAULT_PAGE_SIZE: 20,
  CHAT_MAX_PAGE_SIZE: 50,
  STORIES_DEFAULT_PAGE_SIZE: 20,
} as const;

export type AllowedRadius =
  (typeof COMMUNITY_CONFIG.ALLOWED_RADIUS_OPTIONS)[number];
